-- test/init_db.sql
-- Create a test table for CLOB operations

DROP TABLE CLOB_DATA;

CREATE TABLE CLOB_DATA (
    ID VARCHAR2(255) PRIMARY KEY,
    CONTENT CLOB
);

INSERT INTO CLOB_DATA (ID, CONTENT) VALUES ('1', 'Initial content for ID 1');
INSERT INTO CLOB_DATA (ID, CONTENT) VALUES ('2', 'Initial content for ID 2');
INSERT INTO CLOB_DATA (ID, CONTENT) VALUES ('3', 'Initial content for ID 3');
INSERT INTO CLOB_DATA (ID, CONTENT) VALUES ('4', 'Initial content for ID 4');
INSERT INTO CLOB_DATA (ID, CONTENT) VALUES ('5', 'Initial content for ID 5');
INSERT INTO CLOB_DATA (ID, CONTENT) VALUES ('6', 'Initial content for ID 6');
INSERT INTO CLOB_DATA (ID, CONTENT) VALUES ('7', 'Initial content for ID 7');
INSERT INTO CLOB_DATA (ID, CONTENT) VALUES ('8', 'Initial content for ID 8');
INSERT INTO CLOB_DATA (ID, CONTENT) VALUES ('9', 'Initial content for ID 9');
INSERT INTO CLOB_DATA (ID, CONTENT) VALUES ('10', 'Initial content for ID 10');

DROP TABLE BLOB_DATA;

CREATE TABLE BLOB_DATA (
    ID VARCHAR2(255) PRIMARY KEY,
    CONTENT BLOB
);

INSERT INTO BLOB_DATA (ID, CONTENT) VALUES ('1', utl_raw.cast_to_raw('Initial blob content for ID 1'));

DROP TABLE XMLTYPE_DATA;

CREATE TABLE XMLTYPE_DATA (
    ID VARCHAR2(255) PRIMARY KEY,
    CONTENT XMLTYPE
);

INSERT INTO XMLTYPE_DATA (ID, CONTENT) VALUES ('1', XMLTYPE('<root><item>Initial XML for ID 1</item></root>'));

COMMIT;

EXIT;
